name: "Code-Style Fixer"

on:
    push:
        branches: [ main ]

jobs:
    fix:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Checking PHP Syntax
                uses: TheDragonCode/codestyler@v4
                with:
                    github_token: ${{ secrets.COMPOSER_TOKEN }}
                    fix: true
